version: '3.8'

services:
  account-service:
    build:
      context: ../microservices/account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - charity-network

  donation-service:
    build:
      context: ../microservices/donation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - account-service
      - transaction-service
    networks:
      - charity-network

  transaction-service:
    build:
      context: ../microservices/transaction-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - charity-network

  notification-service:
    build:
      context: ../microservices/notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - charity-network

  ai-damage-detector:
    build:
      context: ../ai-damage-detector
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../ai-damage-detector:/app
    networks:
      - charity-network

  dashboard-frontend:
    build:
      context: ../dashboard-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - account-service
      - donation-service
      - notification-service
      - ai-damage-detector
    networks:
      - charity-network

networks:
  charity-network:
    driver: bridge
